#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "\.jsx\{0,1\}$") | grep -v "^dist/"
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

# Check for eslint
if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install ESlint\033[0m (npm i eslint)"
  exit 1
fi

for FILE in $STAGED_FILES
do
  TEMP_FILE=$(git checkout-index --temp -- $FILE | cut -f 1 -d$'\t')
  "$ESLINT" --ignore-pattern="!$TEMP_FILE" "$TEMP_FILE"

  if [[ "$?" != 0 ]]; then
    printf "\t\033[41mESLint FAILED: $FILE\033[0m\n"
    PASS=false
  fi

  rm $TEMP_FILE
done

if ! $PASS; then
  printf "\n\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
  exit 1
fi

exit $?

